version: "3.8"
services:
  wetware:
    image: wetware/fbx-demo
    container_name: fbx-demo
    network_mode: host
    volumes:
      # Wetware-specific
      - ./wetware:/pkg
      # Dstack-specific
      - /var/run/tappd.sock:/var/run/tappd.sock
      - ${DSTACK_SOCKET}:/var/run/dstack.sock
      - ${TAPPD_SOCKET}:/var/run/tappd.sock
    environment:
      - DSTACK_SIMULATOR_ENDPOINT=/var/run/dstack.sock
      - DEBUG=true
    restart: no
    stdin_open: true
    tty: true
    privileged: true
    working_dir: /pkg

  tiktok-api:
    build: tiktok
    container_name: tiktok-api
    network_mode: host
    volumes:
      - ./api:/api
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /
    command: python -m api.main
