services:
  wetware:
    image: wetware/fbx-demo
    container_name: wetware
    network_mode: host
    volumes:
      # Wetware-specific
      # TODO: copy WASM file to container
      # Dstack-specific
      - /var/run/tappd.sock:/var/run/tappd.sock
      - ${DSTACK_SOCKET}:/var/run/dstack.sock
      - ${TAPPD_SOCKET}:/var/run/tappd.sock
    environment:
      - DSTACK_SIMULATOR_ENDPOINT=/var/run/dstack.sock
      - DEBUG=true
    # cap_add:
    #   - NET_ADMIN
    #   - NET_RAW
    restart: no
    # stdin_open: true
    tty: true
    privileged: true
    working_dir: /pkg
    command: ww start

  tiktok-api:
    image: tikapi/tikapi
    container_name: tikapi
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - API_KEY=${API_KEY}
      - ACCOUNT_KEY=${ACCOUNT_KEY}
      - TIKTOK_HOST=${TIKTOK_HOST}
      - TIKTOK_PORT=${TIKTOK_PORT}
    working_dir: /
    command: python -m tiktok.api.server
    # The command bellow is used to test the pycapnp library
    # command: sh -c "python -m tiktok.api.server & sleep 1s && python -m tiktok.api.test.client"
    restart: no
